const NotificationActionTypes = {
  NOTIFICATION_NEW: "NOTIFICATION_NEW",
  NOTIFICATION_UPDATE_STATUS: "NOTIFICATION_UPDATE_STATUS",
  NOTIFICATION_DELETE: "NOTIFICATION_DELETE"
};

export default NotificationActionTypes;
