export const SHOW_MESSAGE_BOX = "SHOW_MESSAGE_BOX";
export const HIDE_MESSAGE_BOX = "HIDE_MESSAGE_BOX";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
